#!/bin/sh 

#
# Downloads an ISO from a given URL, apply updates on the host and reboot
# Do not run this script on your machine
#
# This script is part of the project Otto
#

# Copyright © 2013 Canonical Ltd.
# Author: Jean-baptiste Lallement <jean-baptiste.lallement@canonical.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

RELEASE=$(lsb_release -sc)
RC=0

usage() {
    # Display usage information
    cat <<EOF
Usage: $(basename $0) BASEURL
This script is intended to be run from Jenkins on a test machine, DO NOT RUN
it on your machine.

This script downloads an Ubuntu Desktop ISO from the given URL for the release
and architecture matching the host system.  Then the system is upgraded and
rebooted.

EOF
    exit 1
}

dl_image() {
    # Download a disk image from a base download URL
    #
    # $1: Base download url (e.g cdimage.ubuntu.com/daily-live/current)

    [ $# -eq 0 ] && return 1
    baseurl=$1
    isoname=$RELEASE-desktop-$(dpkg --print-architecture ).iso
    isodir=$HOME/iso/ubuntu
    name=${JOB_NAME:-$(basename $0)}
    isotmp=$(mktemp $(echo $JOB_NAME|tr '/' '_').XXXXXX)
    devrelease=$(distro-info -d)

    src=$baseurl/$isoname
    dst=$isodir/$isoname
    # Do not re-download the same image for stable releases but always
    # download dev release images
    if [ "$devrelease" = "$RELEASE" -o ! -f "$dst" ]; then
        mkdir -p $isodir
        echo "Downloading $src to $isotmp"
        wget --progress=dot:mega $src -O $isotmp
        if [ -f "$isotmp" ]; then
            mv $isotmp $dst
        else
            echo "E: $src failed to download!"
            return 1
        fi
    fi
    return 0
}

update_system() {
    # Installs updates on the system
    # 
    # @return: 0 on success, 1 on failure

    delay=30
    DEBIAN_FRONTEND=noninteractive
    sudo apt-get update
    ret=$?
    [ $ret -gt 0 ] && return $ret

    # On stable releases there is no really need to reboot every day, only on
    # kernel, drivers and few other packages upgrades 
    if apt-get --simulate dist-upgrade | grep ^Inst; then
        sudo apt-get -y dist-upgrade
        ret=$?
        if [ $ret -eq 0 ]; then
            (echo "Reboot in ${delay}s"; sleep $delay; sudo reboot)&
        fi
    else
        echo "I: No packages to upgrade"
    fi

    return $ret
}

[ $# -eq 0 ] && usage

# Safeguard
echo -n "WARNING: This script will update and reboot your system. You have 10s to
press CTRL+C "
for i in $(seq 10); do
    echo -n "."
    sleep 1
done
echo

dl_image "$1/iso/$RELEASE/"
RC=$?

update_system
RET=$?
[ $RET -ne 0 ] && RC=$RET

exit $RC
